=== MichaelPavlovic/SupportTicket-App/xml/tickets.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="tickets">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ticket" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="ticketID" type="ticket" />
              <xs:element name="dateIssued" type="xs:date" />
              <xs:element name="subject" type="xs:string" />
              <xs:element name="messages">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="message" minOccurs="1" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="username" type="uname" />
                          <xs:element name="time" type="xs:time" />
                          <xs:element name="date" type="xs:date" />
                          <xs:element name="content" type="xs:string" />
                        </xs:sequence>
                        <xs:attribute name="author" type="id" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="status" type="status" />
            <xs:attribute name="author" type="id" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <!--custom types-->
  <xs:simpleType name="status">
    <xs:restriction base="xs:string">
      <xs:enumeration value="ongoing" />
      <xs:enumeration value="resolved" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="id">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]{6}" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="ticket">
    <xs:restriction base="xs:string">
      <xs:pattern value="(t)[0-9]{6}" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="uname">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9A-Za-z ]{3,20}" />
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== MichaelPavlovic/SupportTicket-App/xml/tickets.xml
<?xml version="1.0" encoding="utf-8"?>
<tickets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="tickets.xsd">
  <ticket status="Open" author="000290">
    <ticketID>t026010</ticketID>
    <dateIssued>Mar 17, 2020</dateIssued>
    <subject>Refund</subject>
    <messages>
      <message author="000290">
        <username>JohnDoe3</username>
        <time>10:00PM - Mar 16</time>
        <content>Hello</content>
      </message>
      <message author="031201">
        <username>Admin</username>
        <time>10:40PM - Mar 16</time>
        <content>Hi, what can I help you with?</content>
      </message>
    <message author="031201"><username>Admin</username><time>09:54PM - Mar 17</time><content>test</content></message></messages>
  </ticket>
  <ticket status="Open" author="001110">
    <ticketID>t012010</ticketID>
    <dateIssued>Mar 10, 2020</dateIssued>
    <subject>Password</subject>
    <messages>
      <message author="001110">
        <username>Michael</username>
        <time>1:00PM - Mar 10</time>
        <content>Hey can you help me with something?</content>
      </message>
    </messages>
  </ticket>
</tickets>
