=== MichaelPavlovic/SupportTicket-App/xml/users.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="users">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="user" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="id" type="id" />
              <xs:element name="username" type="uname" />
              <xs:element name="password" type="pword" />
              <xs:element name="email" type="email" />
            </xs:sequence>
            <xs:attribute name="type" type="userType" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:simpleType name="userType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="client" />
      <xs:enumeration value="admin" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="id">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]{6}" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="uname">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9A-Za-z ]{3,20}" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="pword">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9A-Za-z!_.$/]{5,100}" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="email">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9A-Za-z_]{3,}\@[A-Za-z]{3,}\.(com|ca|org|net)" />
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== MichaelPavlovic/SupportTicket-App/xml/users.xml
<?xml version="1.0" encoding="utf-8" ?>
<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="users.xsd">
  <user type="admin">
    <id>031201</id>
    <username>Admin</username>
    <password>$2y$10$f8YI.bHTk.4nVfHmp0FEkO0Xg/zYNTwS5DxH4fog88dbHKjMRkPJW</password>
    <email>admin@gmail.com</email>
  </user>
  <user type="client">
    <id>000290</id>
    <username>JohnDoe3</username>
    <password>$2y$10$IxVuoiEHuNjIjEmlshKxSu3Kt6uITrv8vMpUyanXqF0wb0Ov7yr1S</password>
    <email>johndoe3@gmail.com</email>
  </user>
  <user type="client">
    <id>001110</id>
    <username>Michael</username>
    <password>$2y$10$9ZGf6nQ37xYNpYSpWCGXvOGqGll43E4ZOfyNGJmbBut2MxBBXXyvq</password>
    <email>michael@gmail.com</email>
  </user>
</users>
